settings:
  model_path: /workspaces/modalities/checkpoints/2_6B_DE/2_6B_DE.bin
  max_new_tokens: 512
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}


model:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: input_ids
    poe_type: NOPE
    block_size: 2048
    prediction_key: logits
    vocab_size: 100352 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 32
    n_head_q: 32
    n_head_kv: 32
    ffn_hidden: 6656
    n_embd: 2560
    dropout: 0.0
    epsilon: 1e-5
    bias: false # True: bias in Linears and LayerNorms, like GPT-2. False: a bit better and faster
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform
          config:
            n_embd: ${model.config.n_embd}
            n_head: ${model.config.n_head_q}
            seq_length_dim: -2
    activation_type: fused_swiglu
    weight_init:
      mean: 0.0
      std:  0.0158
    attention_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_sp_tokenizer
  config:
    tokenizer_model_file: /workspaces/modalities/checkpoints/tokenizer/unigram_tokenizer.model
    padding: false
    max_length: 512
