settings:
  referencing_keys:
    sample_key: input_ids
    prediction_key: logits
  model_path: /raid/s3/opengptx/max_lue/modalities/data/checkpoints/2024-04-22__13-16-03/eid_2024-04-22__13-16-03-model-num_steps_1152.bin
  device: 0
  sequence_length: 2048

text_inference_component:
  component_key: inference_component
  variant_key: text
  config:
    device: ${settings.device}
    model:
      instance_key: checkpointed_model
      pass_type: BY_REFERENCE
    tokenizer:
      instance_key: tokenizer
      pass_type: BY_REFERENCE
    sequence_length: ${settings.sequence_length}
    eod_token: <eod>
    prompt_template: "{prompt_input}" # "<instruction> Du bist Moody, ein LLM welches Menschen helfen soll. user: {prompt_input}"
    temperature: 0
    # chat: false

checkpointed_model:
  component_key: model
  variant_key: checkpointed
  config: 
    checkpoint_loading:
      component_key: checkpoint_loading
      variant_key: torch
      config:
        device: ${settings.device}
        precision: BF16
    model:
      instance_key: raw_model
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.model_path}

raw_model:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: ABSOLUTE
    sequence_length: ${settings.sequence_length}
    prediction_key: ${settings.referencing_keys.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 12
    n_head_q: 12
    n_head_kv: 12
    ffn_hidden: 2048
    n_embd: 768
    dropout: 0.0
    bias: true # True: bias in Linears, like GPT-2. False: a bit better and faster
    attention_config:
      qkv_transforms:
        - type_hint: IdentityTransform
          config: {}
    activation_type: gelu
    attention_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${raw_model.config.n_embd}
        bias: true
        epsilon: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${raw_model.config.n_embd}
        bias: true
        epsilon: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${raw_model.config.n_embd}
        bias: true
        epsilon: 1e-5

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: /raid/s3/opengptx/max_lue/modalities/data/tokenizer/hf_gpt2
    padding: false
    truncation: false
