settings:
  model_path: /workspaces/modalities/checkpoints/2_6B_DE/2_6B_DE.bin
  max_new_tokens: 512
  eod_token: <eod>
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}


checkpointed_model:
  component_key: model
  variant_key: checkpointed
  config: 
    checkpoint_loading:
      component_key: checkpoint_loading
      variant_key: torch
      config:
        device: 7
    model:
      instance_key: raw_model
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.model_path}


raw_model:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    block_size: ${settings.training.sequence_length}
    prediction_key: ${settings.referencing_keys.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 12
    n_head_q: 12
    n_head_kv: 12
    ffn_hidden: 2048
    n_embd: 768
    dropout: 0.0
    bias: true # True: bias in Linears, like GPT-2. False: a bit better and faster
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform
          config:
            n_embd: ${model.config.n_embd}
            n_head: ${model.config.n_head_q} #it has to be head_q here
            seq_length_dim: -2
    activation_type: gelu
    weight_init:
      mean: 0.0
      std: 0.02
    attention_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
tokenizer:
  component_key: tokenizer
  variant_key: pretrained_sp_tokenizer
  config:
    tokenizer_model_file: /workspaces/modalities/data/tokenizer/endefrites_bpe/bpe_tokenizer 1.model
    padding: false
    max_length: 512
