settings:
  src_path: data/raw/fineweb_edu_num_docs_483606.jsonl
  dst_path: data/preprocessed/fineweb_edu_num_docs_483606.pbin
  index_path: data/preprocessed/fineweb_edu_num_docs_483606.idx
  jq_pattern: .text
  num_cpus: ${node_env:num_cpus}
  eod_token: <|endoftext|>
  processing_batch_size: 10
  raw_samples_queue_size: 300
  processed_samples_queue_size: 300

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: data/tokenizer
    padding: false
    truncation: false