settings:  
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    training_log_interval_in_steps: 64
    checkpointing_interval_in_steps: 64
    evaluation_interval_in_steps: 64
    global_num_seen_tokens: 0
    do_apply_activation_checkpointing: false
    gradient_acc_steps: 1
    local_train_micro_batch_size: 8
    sequence_length: 512
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: ./checkpoints

collate_fn:  
  component_key: collate_fn
  variant_key: span_masking_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}
    noise_density:  0.15
    mean_noise_span_length: 3.0
    tokenizer:
      instance_key: tokenizer
      pass_type: BY_REFERENCE


# collate_fn_wrapped:  
#   component_key: collate_fn
#   variant_key: denoise_collator_wrapper
#   config:
#     target_keys_to_mask: ["${settings.referencing_keys.target_key}"]
#     noise_density: 0.15
#     loss_ignore_index: -100
#     collate_fn:
#       instance_key: collate_fn
#       pass_type: BY_REFERENCE
#     tokenizer:
#       instance_key: tokenizer
#       pass_type: BY_REFERENCE

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: ./data_llama/mem_map/redpajama_v2_samples_512_train.pbin
    # raw_data_path: ../../data/lorem_ipsum_long.pbin
    sequence_length: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: repeating_data_loader
  config:
    reshuffle_after_epoch: false
    num_epochs: 1
    dataloader:
      component_key: data_loader
      variant_key: default
      config:
        num_workers: 2
        pin_memory: true
        shuffle: false
        dataloader_tag: "train"
        dataset:
          instance_key: train_dataset
          pass_type: BY_REFERENCE
        batch_sampler:
          component_key: batch_sampler
          variant_key: default
          config:
            batch_size: ${settings.training.local_train_micro_batch_size}
            drop_last: true
            sampler:
              component_key: sampler
              variant_key: distributed_sampler
              config:
                rank: ${settings.cuda_env.global_rank}
                num_replicas: ${settings.cuda_env.world_size}
                shuffle: true
                dataset:
                  instance_key: train_dataset
                  pass_type: BY_REFERENCE
        collate_fn:
          instance_key: collate_fn
          pass_type: BY_REFERENCE


val_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: ./data_t5/mem_map/redpajama_v2_samples_512_test.pbin
    # raw_data_path: ../../data/lorem_ipsum.pbin
    sequence_length: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1   # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        get_num_tokens_from_num_steps_callable:
          component_key: number_conversion
          variant_key: num_tokens_from_num_steps_callable
          config:
            num_ranks: ${settings.cuda_env.world_size}
            local_micro_batch_size: ${settings.training.local_train_micro_batch_size}
            sequence_length: ${settings.training.sequence_length}        

# resolving class types via different enums sucks...
loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: target_ids
    prediction_key: logits

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD
    block_names: [LongT5Block]

model_raw:
  component_key: model
  variant_key: huggingface_pretrained_encoder_decoder_model
  config:
    #model_type: AutoModelForCausalLM
    #model_name: TinyLlama/TinyLlama_v1.1 
    model_type: LongT5ForConditionalGeneration
    model_name: google/long-t5-tglobal-base
    sample_key: ${settings.referencing_keys.sample_key}
    prediction_key: logits
    huggingface_prediction_subscription_key: logits

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: tokenizer_t5
    padding: false
    truncation: false

#scheduler:
#  component_key: scheduler
#  variant_key: step_lr
#  config:
#    optimizer:
#      instance_key: optimizer
#      pass_type: BY_REFERENCE
#    step_size: 1
#    gamma: 0.1

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 6e-4
    div_factor: 10
    final_div_factor: 1
    total_steps: 256
    pct_start: 0.01
    anneal_strategy: cos

optimizer:  
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    # need to fix in huggingface_model.py to same spec as in gpt2_model.py
    # setting to empty list works for now
    weight_decay_groups_excluded: ["embedding", "layernorm"]
    wrapped_model: 
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    #local_rank: ${settings.cuda_env.local_rank}
    #world_size: ${settings.cuda_env.world_size}
    global_rank: ${settings.cuda_env.global_rank}
    global_num_seen_steps:
      component_key: number_conversion
      variant_key: num_steps_from_num_tokens
      config:
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.training.local_train_micro_batch_size}
        global_num_tokens: ${settings.training.global_num_seen_tokens}
        sequence_length: ${settings.training.sequence_length}
    gradient_acc_steps: ${settings.training.gradient_acc_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
        instance_key: eval_dataloaders
        pass_type: BY_REFERENCE

    
evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    #local_rank: ${settings.cuda_env.local_rank}
    global_rank: ${settings.cuda_env.global_rank}
    project: modalities_getting_started
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: "."
    config_file_path: ${settings.config_file_path}
