settings:
  src_path: data/lorem_ipsum_sft.jsonl
  dst_path: data/lorem_ipsum_sft_converted.jsonl
  conversations_key: 'conversations'
  chat_template_key: null

instruction_data_transformation:
  role_mapping:
    human_1: User1
    human_2: User2
    gpt: Assistant

# The b_assistant_token, e_assistant_token and eod_token are required to be part of each chat template for proper loss masking!
jinja2_chat_template_files: 
  default: config_files/data_preparation/default_chat_template.jinja
  # code: config_files/data_preparation/code_chat_template.jinja
  # extraction: config_files/data_preparation/material_chat_template.jinja
  # ...

# The key-value pairs of chat_template_data are passed to the Jinja2 template and 
# are not type checked for full compliance with the chat tempalate!
chat_template_data:
  assistant_role: Assistant
  system_instruction: "You are Mody, a helpful assistant trained by the modalities team. Answer friendly and informatively to the user's messages."
  special_tokens:
      b_assistant_token: <i>
      e_assistant_token: </i>
      eod_token: <|endoftext|>
