settings:
  src_path: /raid/s3/opengptx/alignment_data/data/honey/data/en/ultrachat_200k_fastchat_56696d6/ultrachat_200k_fastchat_converted.56696d5.jsonl
  dst_path: /raid/s3/opengptx/alignment_data/data/honey/data/en/ultrachat_200k_fastchat_56696d6/ultrachat_200k_fastchat_converted.56696d5.pbin
  index_path: /raid/s3/opengptx/alignment_data/data/honey/data/en/ultrachat_200k_fastchat_56696d6/ultrachat_200k_fastchat_converted.56696d5.idx
  jq_pattern: .chat
  num_cpus: 100 # ${node_env:num_cpus}
  eod_token: <|endoftext|>
  processing_batch_size: 10
  raw_samples_queue_size: 300
  processed_samples_queue_size: 300
  sequence_length: 2048

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: HuggingFaceTB/SmolLM-1.7B
    padding: max_length
    truncation: true
    max_length: ${settings.sequence_length}
    special_tokens:
      pad_token: ${settings.eod_token}
      additional_special_tokens:
        - "<|im_start|>"
        - "<|im_end|>"