settings:
  src_path: data/lorem_ipsum.jsonl
  dst_path: data/lorem_ipsum.pbin
  index_path: data/lorem_ipsum.idx
  jq_pattern: .text
  num_cpus: ${node_env:num_cpus}
  eod_token: <|endoftext|>
  processing_batch_size: 10
  raw_samples_queue_size: 20
  processed_samples_queue_size: 20

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: data/tokenizer/hf_gpt2
    padding: false
    truncation: false
