settings:
  src_path: data/postprocessed_fine_web_10BT_10.jsonl
  dst_path: data/postprocessed_fine_web_10BT_10.pbin
  index_path: data/postprocessed_fine_web_10BT_10.idx
  jq_pattern: .text
  num_cpus: 5
  eod_token: <|endoftext|>
  processing_batch_size: 100
  raw_samples_queue_size: 100
  processed_samples_queue_size: 100


tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: data/tokenizer/hf_gpt2
    padding: false
    truncation: false
