settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpoint_saving_path: data/checkpoints
    train_dataset_path: ./data/lorem_ipsum.pbin
  intervals:
    training_log_interval_in_steps: 128
    checkpointing_interval_in_steps: 128
    evaluation_interval_in_steps: 129
  consistency_enforcement:
    enforce_tokens_per_step_consistency: true
    enforce_last_step_logged: false
    enforce_last_step_evaluated: false
    enforce_last_step_checkpointed: false
  step_profile: 
    gradient_accumulation_steps: 32
    local_train_micro_batch_size: 16
    sequence_length: 1536
  training_target:
    num_target_tokens:
      component_key: number_conversion
      variant_key: num_tokens_from_num_steps
      config:
        num_steps: ${settings.training_target.num_target_steps}
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.step_profile.local_train_micro_batch_size}
        sequence_length: ${settings.step_profile.sequence_length}
        gradient_accumulation_steps: ${settings.step_profile.gradient_accumulation_steps}
    num_target_steps:  # for the batch progress subscriber
      component_key: number_conversion
      variant_key: num_steps_from_num_samples
      config:
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.step_profile.local_train_micro_batch_size}
        global_num_samples: ${settings.coca_example_settings.train_num_samples}
        gradient_accumulation_steps: ${settings.step_profile.gradient_accumulation_steps}
  training_progress: 
    global_num_seen_tokens: 0
    num_seen_steps: 0
    local_num_seen_batches: 0
    last_step: -1
  coca_example_settings:
    train_num_samples: 3608326
    val_num_samples: 1000

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: TinyLlama/TinyLlama_v1.1
    padding: true
    max_length: ${settings.step_profile.sequence_length}

collate_fn:
  component_key: collate_fn
  variant_key: anymal_collator
  config:
    sample_keys:
      - images
      - ${settings.referencing_keys.sample_key}
    text_sample_key: ${settings.referencing_keys.sample_key}
    text_target_key: ${settings.referencing_keys.target_key}

train_image_transform:
  component_key: transform
  variant_key: image_transform
  config:
    is_training: True
    input_size: 384
    crop_mode: 'center'
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

val_image_transform:
  component_key: transform
  variant_key: image_transform
  config:
    is_training: False
    input_size: 384
    crop_mode: 'center'
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    hflip: 0.0


text_transform:
  component_key: transform
  variant_key: multimodal_text_transform
  config:
    tokenizer:
      instance_key: tokenizer
      pass_type: BY_REFERENCE
    n_image_tokens: ${image_projector_model.config.n_latents}
    max_length: ${settings.step_profile.sequence_length}
    truncation: true

train_llavainstruct_dataset_builder:
  component_key: dataset
  variant_key: web_dataset_builder
  config:
    urls: "000000.tar"
    flatten_text_dict: False
    modality_key_mapping:
      TEXT: ["json", "input_ids"]
      IMAGE: ["jpg", "images"]
    modality_transforms:
      IMAGE:
        instance_key: train_image_transform
        pass_type: BY_REFERENCE
      TEXT:
        instance_key: text_transform
        pass_type: BY_REFERENCE
    num_samples: 650000


train_dataset:
  component_key: dataset
  variant_key: web_dataset
  config:
    builders:
      - instance_key: train_llavainstruct_dataset_builder
        pass_type: BY_REFERENCE
    shardshuffle: 100
    repeat: true
    resample: true
    shuffle_buffer: 10_000

val_llavainstruct_dataset_builder:
  component_key: dataset
  variant_key: web_dataset_builder
  config:
    urls: "000001.tar"
    flatten_text_dict: False
    modality_key_mapping:
      TEXT: ["json", "input_ids"]
      IMAGE: ["jpg", "images"]
    modality_transforms:
      IMAGE:
        instance_key: val_image_transform
        pass_type: BY_REFERENCE
      TEXT:
        instance_key: text_transform
        pass_type: BY_REFERENCE
    num_samples: 1000

val_dataset:
  component_key: dataset
  variant_key: web_dataset
  config:
    builders:
      - instance_key: val_llavainstruct_dataset_builder
        pass_type: BY_REFERENCE
    shardshuffle: 1000
    repeat: false
    resample: false
    shuffle_buffer: 10_000

train_dataloader:
  component_key: data_loader
  variant_key: web_dataloader
  config:
    num_workers: 8
    pin_memory: true
    drop_last: true
    dataloader_tag: "train"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_size: ${settings.step_profile.local_train_micro_batch_size}
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: web_dataloader
  config:
    num_workers: 8
    pin_memory: true
    drop_last: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_size: ${settings.step_profile.local_train_micro_batch_size}
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1 # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: ddp
      config:
        checkpoint_path: ${settings.paths.checkpoint_saving_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        submodule: image_projector
        lora_submodule: text_decoder

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${model_raw.config.prediction_key}


wrapped_model:
  component_key: model
  variant_key: ddp_wrapped
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    mixed_precision_settings: BF_16
    local_rank: ${settings.cuda_env.local_rank}

image_projector_model:
  component_key: model
  variant_key: perceiver
  config:
    n_embd: 1152
    n_head: 8
    n_layer: 6
    n_latents: 64
    n_frames: 1
    block_size: 728
    ffn_hidden: 3072
    bias: true
    dropout: 0.1
    attention_config:
      attention_engine_type: default_attention
    output_n_embd: 2048


model_raw:
  component_key: model
  variant_key: anymal
  config:
    image_encoder:
      component_key: model
      variant_key: huggingface_pretrained_model
      config:
        model_type: SiglipVisionModel
        model_name: google/siglip-so400m-patch14-384
        prediction_key: hidden_states
        huggingface_prediction_subscription_key: hidden_states
        sample_key: images
    text_decoder:
      component_key: model
      variant_key: huggingface_pretrained_model
      config:
        model_type: AutoModelForCausalLM
        model_name: TinyLlama/TinyLlama_v1.1
        prediction_key: ${settings.referencing_keys.prediction_key}
        huggingface_prediction_subscription_key: logits
        sample_key: ${settings.referencing_keys.sample_key}
    image_projector:
      component_key: model
      variant_key: torch_model
      config:
        model: 
          instance_key: image_projector_model
          pass_type: BY_REFERENCE
        device: 'cpu'
    prediction_key: ${settings.referencing_keys.prediction_key}
    model_mode: INSTRUCTION_TUNING_TRAINING

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 2e-4
    div_factor: 10
    final_div_factor: 1000
    total_steps: ${settings.training_target.num_target_steps}
    pct_start: 0.04
    anneal_strategy: cos
    last_epoch: ${settings.training_progress.last_step}

optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 2e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 1e-1
    weight_decay_groups_excluded: [embedding, norm, parameter]
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: torch
  config:
    model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

progress_subscriber:
  component_key: progress_subscriber
  variant_key: simple
  config:
    global_rank: ${settings.cuda_env.global_rank}
    num_seen_steps: ${settings.training_progress.num_seen_steps}
    num_target_steps: ${settings.training_target.num_target_steps}
    train_dataloader_tag: ${train_dataloader.config.dataloader_tag}
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    global_rank: ${settings.cuda_env.global_rank}
    project: modalities_anymal
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: wandb_storage
    config_file_path: ${settings.config_file_path}
