settings:  
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    global_training_log_interval_in_steps: 8
    global_checkpointing_interval_in_steps: 3
    global_evaluation_interval_in_steps: 2
    global_num_seen_steps: 0
    do_apply_activation_checkpointing: true
    gradient_acc_steps: 1
    local_train_micro_batch_size: 1
    sequence_length: 256
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: data/checkpoints

collate_fn:  
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: ./data/lorem_ipsum.pbin
    block_size: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "train"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: true
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: 4
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

test_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "test"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: 2
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE
  - instance_key: test_dataloader
    pass_type: BY_REFERENCE 

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1   # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id} 

# resolving class types via different enums sucks...
loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: target_ids
    prediction_key: logits

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD
    block_names: [TransformerBlock]

model:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    block_size: ${settings.training.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 2
    n_head_q: 8
    n_head_kv: 4
    ffn_hidden: 128
    n_embd: 128
    dropout: 0.0
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform
          config:
            n_embd: ${model.config.n_embd}
            n_head: ${model.config.n_head_q} #it has to be head_q here
            seq_length_dim: -2
    weight_init:
      mean: 0.0
      std: 0.02
    lm_head_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    gpt2block:
      component_key: block
      variant_key: transformer_block
      config:
        block_size: ${settings.training.sequence_length}
        n_embd: ${model.config.n_embd}
        attention_norm:
          component_key: layer_norm
          variant_key: rms_norm
          config:
            ndim: ${model.config.n_embd}
            bias: true
            epsilon: 1e-5
        ffn_norm:
          component_key: layer_norm
          variant_key: rms_norm
          config:
            ndim: ${model.config.n_embd}
            bias: true
            epsilon: 1e-5
        attention_config: ${model.config.attention_config}
        dropout: ${model.config.dropout}
        ffn_hidden: 128
        bias: true # True: bias in Linears and LayerNorms, like GPT-2. False: a bit better and faster
        n_head_q: ${model.config.n_head_q}
        n_head_kv: 8

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 6e-4
    div_factor: 10
    final_div_factor: 1
    total_steps: 32
    pct_start: 0.01
    anneal_strategy: cos

optimizer:  
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    wrapped_model: 
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    local_rank: ${settings.cuda_env.local_rank}
    global_num_seen_steps: ${settings.training.global_num_seen_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
        instance_key: eval_dataloaders
        pass_type: BY_REFERENCE

    
evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    local_rank: ${settings.cuda_env.local_rank}
    project: modalities_lorem_ipsum
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: "."
    config_file_path: ${settings.config_file_path}
