settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    global_training_log_interval_in_steps: 4
    global_checkpointing_interval_in_steps: 5_000
    global_evaluation_interval_in_steps: 5_000
    global_num_training_samples: 102_400
    global_num_seen_steps: 0
    do_apply_activation_checkpointing: true
    gradient_acc_steps: 1
    local_train_micro_batch_size: 144
    sequence_length: 256
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: data/checkpoints

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: gpt2
    padding: true
    max_length: 256

collate_fn:
  component_key: collate_fn
  variant_key: coca_collator
  config:
    sample_keys:
      - images
      - ${settings.referencing_keys.sample_key}
      - modality
    target_keys: []
    text_sample_key: ${settings.referencing_keys.sample_key}
    text_target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: dummy_dataset
  config:
    num_samples: 10_000
    sample_definition:
      - sample_key: images
        sample_shape: [3, 256, 256]
        sample_type: float
      - sample_key: input_ids
        sample_shape: [256]
        sample_type: int
      - sample_key: modality
        sample_shape: [0]
        sample_type: const

val_dataset:
  component_key: dataset
  variant_key: dummy_dataset
  config:
    num_samples: 1_000
    sample_definition:
      - sample_key: images
        sample_shape: [3, 256, 256]
        sample_type: float
      - sample_key: input_ids
        sample_shape: [256]
        sample_type: int
      - sample_key: modality
        sample_shape: [0]
        sample_type: const

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "train"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: true
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1 # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        mixed_precision_settings: FP_16
        sharding_strategy: HYBRID_SHARD
        block_names: [TransformerBlock, VisionTransformerBlock]

captioning_loss:
  component_key: loss
  variant_key: cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${model.config.prediction_key}
    tag: captioning_loss

contrastive_loss:
  component_key: loss
  variant_key: clip_loss
  config:
    prediction_key1: ${model.config.vision_cls_prediction_key}
    prediction_key2: ${model.config.text_cls_prediction_key}
    logit_scale_key: ${model.config.logit_scale_prediction_key}
    tag: contrastive_loss

loss_fn:
  - instance_key: captioning_loss
    pass_type: BY_REFERENCE
  - instance_key: contrastive_loss
    pass_type: BY_REFERENCE

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: FP_16
    sharding_strategy: HYBRID_SHARD
    block_names: [TransformerBlock, VisionTransformerBlock]

model:
  component_key: model
  variant_key: coca
  config:
    prediction_key: logits
    modality_key: modality
    modality_embd_prediction_key: modality_embeddings
    text_embd_prediction_key: text_embeddings
    modality_cls_prediction_key: modality_cls
    text_cls_prediction_key: text_cls
    modality_encoder_config:
      sample_key: images
      prediction_key: modality_embeddings
      img_size: 256 # 288 in the original coca
      n_classes: Null # Disable vision transformer head
      n_layer: 12
      attention_config:
        attention_engine_type: default_attention
      n_head: 12
      n_embd: 768
      dropout: 0.0
      patch_size: 16 # 18 in the original coca
      patch_stride: 16 # 18 in the original coca
      n_img_channels: 3
      add_cls_token: False
      bias: True
    text_decoder_config:
      sample_key: ${settings.referencing_keys.sample_key}
      prediction_key: ${model.config.prediction_key}
      block_size: 1024
      vocab_size: 50304 # 64k in the original coca
      n_layer_text: 12
      n_layer_multimodal_text: 12
      attention_config:
        attention_engine_type: default_attention
      n_head: 12
      ffn_hidden: 2048
      n_embd: 768
      dropout: 0.0
      bias: true
      activation: fused_swiglu
      epsilon: 1e-5
    n_pool_head: 12
    n_vision_queries: 256
    n_audio_queries: Null
    bias_attn_pool: False
    epsilon_attn_pool: 1e-5
    weight_init:
      mean: 0.0
      std: 0.02

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr # COCA uses linear decay
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 8e-4
    div_factor: 10
    final_div_factor: 1
    total_steps: 500_000 # depends on 500.000 iterations on 65,536 image-text pairs -> 5 epochs on JFT -> 32.7B image-text pairs
    pct_start: 0.02
    anneal_strategy: cos

optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 8e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.01
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp_logging_only
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM

batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    local_rank: ${settings.cuda_env.global_rank}
    world_size: ${settings.cuda_env.world_size}
    global_num_seen_steps: ${settings.training.global_num_seen_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    local_rank: ${settings.cuda_env.global_rank}
    project: modalities
    mode: ONLINE
    experiment_id: ${settings.experiment_id}
    directory: "."
    config_file_path: ${settings.config_file_path}
