settings:
  experiment_id: ${modalities_env:experiment_id}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  training:
    global_training_log_interval_in_steps: 10
    global_checkpointing_interval_in_steps: 1000
    global_evaluation_interval_in_steps: 64
    global_num_seen_steps: 0
    activation_checkpointing_modules: []
    gradient_acc_steps: 1
    local_train_micro_batch_size: 4
    sequence_length: 0 # TODO: Is sequence_length used in training?
    gradient_clipping:
      mode: p2_norm
      threshold: 1.0
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: data/checkpoints

collate_fn:
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/fhgiais/opengptx/michaelf/git_repos/modalities/data-temp/en/modalities/2048/train_2048.pbin
    block_size: ${settings.training.sequence_length}
    sample_key: ${settings.referencing_keys.sample_key}

val_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/fhgiais/opengptx/michaelf/git_repos/modalities/data-temp/en/modalities/2048/valid_2048.pbin
    block_size: ${settings.training.sequence_length}
    sample_key: ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: repeating_data_loader
  config:
    reshuffle_after_epoch: false
    num_epochs: 1 # 100 epochs
    dataloader:
      component_key: data_loader
      variant_key: default
      config:
        num_workers: 2
        pin_memory: true
        shuffle: false
        dataloader_tag: train
        dataset:
          instance_key: train_dataset
          pass_type: BY_REFERENCE
        batch_sampler:
          component_key: batch_sampler
          variant_key: default
          config:
            batch_size: ${settings.training.local_train_micro_batch_size}
            drop_last: true
            sampler:
              component_key: sampler
              variant_key: distributed_sampler
              config:
                rank: ${settings.cuda_env.global_rank}
                num_replicas: ${settings.cuda_env.world_size}
                shuffle: true
                dataset:
                  instance_key: train_dataset
                  pass_type: BY_REFERENCE
        collate_fn:
          instance_key: collate_fn
          pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: val
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE


checkpointing:
  component_key: checkpointing
  variant_key: default
  config:
    checkpointing_strategy:
      component_key: checkpointing_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: 3   # -1 to save all checkpoints
    checkpointing_execution:
      component_key: checkpointing_execution
      variant_key: fsdp_to_disc_checkpointing
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        mixed_precision_settings: BF_16
        sharding_strategy: FULL_SHARD
        block_names: [ MambaBlock ]

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD
    block_names: [ MambaBlock ]

model:
  component_key: model
  variant_key: mamba
  config:
    d_model: 768
    n_layer: 24
    vocab_size: 50257
    rms_norm: true
    residual_in_fp32: true
    fused_add_norm: true
    pad_vocab_size_multiple: 8
    tie_embeddings: true
    prediction_key: ${settings.referencing_keys.prediction_key}
    sample_key: ${settings.referencing_keys.sample_key}
    seed: null
    dtype: null
    initializer_cfg: {}
    num_last_tokens: 0
    inference_params: {}
    mixer_model_config:
      norm_epsilon: 1e-5
      device: null
      mamba_block_config:
        d_state: 16
        d_conv: 4
        expand: 2
        dt_rank: auto
        dt_min: 0.001
        dt_max: 0.1
        dt_init: random
        dt_scale: 1.0
        dt_init_floor: 1e-4
        conv_bias: true
        bias: false
        use_fast_path: true

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [ 0.9, 0.95 ]
    eps: 1e-8
    weight_decay: 1e-1
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

scheduler:
  component_key: scheduler
  variant_key: dummy_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE


batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    local_rank: ${settings.cuda_env.local_rank}
    world_size: ${settings.cuda_env.world_size}
    global_num_seen_steps: ${settings.training.global_num_seen_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
      - instance_key: val_dataloader
        pass_type: BY_REFERENCE


evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    local_rank: ${settings.cuda_env.local_rank}
    project: modalities
    mode: ONLINE
    experiment_id: ${settings.experiment_id}
    directory: "."