settings:  
  experiment_id: ${modalities_env:experiment_id}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  training:
    training_log_interval_in_steps: 32
    checkpointing_interval_in_steps: 8192
    evaluation_interval_in_steps: 1024
    global_num_seen_tokens: 0
    do_apply_activation_checkpointing: false
    gradient_acc_steps: 1
    local_train_micro_batch_size: 16
    sequence_length: 2048
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: data/checkpoints

collate_fn:  
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/s3/opengptx/max_lue/modalities/data/sample_datasets/redpajama_v2/mem_map/redpajama_v2_default_DE_num_docs_1050391/redpyjama_v2_sample_1050391.pbin
    block_size: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: repeating_data_loader
  config:
    reshuffle_after_epoch: false
    num_epochs: 100
    dataloader:
      component_key: data_loader
      variant_key: default
      config:
        num_workers: 2
        pin_memory: true
        shuffle: false
        dataloader_tag: "train"
        dataset:
          instance_key: train_dataset
          pass_type: BY_REFERENCE
        batch_sampler:
          component_key: batch_sampler
          variant_key: default
          config:
            batch_size: ${settings.training.local_train_micro_batch_size}
            drop_last: true
            sampler:
              component_key: sampler
              variant_key: distributed_sampler
              config:
                rank: ${settings.cuda_env.global_rank}
                num_replicas: ${settings.cuda_env.world_size}
                shuffle: true
                dataset:
                  instance_key: train_dataset
                  pass_type: BY_REFERENCE
        collate_fn:
          instance_key: collate_fn
          pass_type: BY_REFERENCE

val_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/s3/opengptx/max_lue/modalities/data/sample_datasets/redpajama_v2/mem_map/redpyjama_v2_default_DE_num_docs_1024/redpyjama_v2_default_DE_num_docs_1024.pbin
    block_size: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1   # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id} 

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD
    block_names: [GPT2Block]

model:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: ABSOLUTE
    block_size: ${settings.training.sequence_length}
    prediction_key: ${settings.referencing_keys.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 12
    n_head_q: 12
    n_head_kv: 12
    ffn_hidden: 2048
    n_embd: 768
    dropout: 0.0
    bias: true # True: bias in Linears, like GPT-2. False: a bit better and faster
    attention_config:
      qkv_transforms: []
        # - type_hint: RotaryTransform
        #   config:
        #     n_embd: ${model.config.n_embd}
        #     n_head: ${model.config.n_head_q} #it has to be head_q here
        #     seq_length_dim: -2
    activation_type: gelu
    weight_init:
      mean: 0.0
      std: 0.02
    attention_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: rms_norm
      config:
        ndim: ${model.config.n_embd}
        bias: true
        epsilon: 1e-5

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

optimizer:  
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.000001
    betas: [0.9, 0.99]
    eps: 1e-8
    weight_decay: 1e-2
    wrapped_model: 
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

scheduler:
  component_key: scheduler
  variant_key: dummy_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0
    


batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    local_rank: ${settings.cuda_env.local_rank}
    world_size: ${settings.cuda_env.world_size}
    global_num_seen_steps:
      component_key: number_conversion
      variant_key: num_steps_from_num_tokens
      config:
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.training.local_train_micro_batch_size}
        global_num_tokens: ${settings.training.global_num_seen_tokens}
        context_size: ${settings.training.sequence_length}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
      - instance_key: val_dataloader
        pass_type: BY_REFERENCE

    
evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    local_rank: ${settings.cuda_env.local_rank}
    project: modalities
    mode: ONLINE
    experiment_id: ${settings.experiment_id}
    directory: "."