settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    training_log_interval_in_steps: 2
    checkpointing_interval_in_steps: 4
    evaluation_interval_in_steps: 2
    global_num_seen_tokens: 0
    activation_checkpointing_modules: [GPT2Block]
    gradient_acc_steps: 2
    local_train_micro_batch_size: 1
    sequence_length: 256
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: /raid/s3/opengptx/models/modalities/2.7B_EN_DCLM/2.7B_EN_DCLM/

collate_fn:
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/s3/opengptx/alignment_data/data/honey/data/en/ultrachat_200k_fastchat_74d2208/ultrachat_200k_fastchat_converted_train.74d2208.pbin
    sequence_length: ${settings.training.sequence_length}
    sample_key:  ${settings.referencing_keys.sample_key}

val_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_continuous
  config:
    raw_data_path: /raid/s3/opengptx/alignment_data/data/honey/data/en/ultrachat_200k_fastchat_74d2208/ultrachat_200k_fastchat_converted_val.74d2208.pbin
    sequence_length: ${settings.training.sequence_length}
    sample_key: ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "train"
    skip_num_batches:
      instance_key: skip_num_batches
      pass_type: BY_REFERENCE
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    fixed_num_batches: 100
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: 6
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_loading:
  component_key: checkpoint_loading
  variant_key: fsdp
  config:
    global_rank: ${settings.cuda_env.global_rank}
    block_names: [GPT2Block]
    mixed_precision_settings: FP_32
    sharding_strategy: HYBRID_SHARD

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1   # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        get_num_tokens_from_num_steps_callable:
          component_key: number_conversion
          variant_key: num_tokens_from_num_steps_callable
          config:
            num_ranks: ${settings.cuda_env.world_size}
            local_micro_batch_size: ${settings.training.local_train_micro_batch_size}
            sequence_length: ${settings.training.sequence_length}
loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: logits

skip_num_batches:
  component_key: number_conversion
  variant_key: local_num_batches_from_num_tokens
  config:
    num_ranks: ${settings.cuda_env.world_size}
    global_num_tokens: ${settings.training.global_num_seen_tokens}
    sequence_length: ${settings.training.sequence_length}
    local_micro_batch_size: ${settings.training.local_train_micro_batch_size}

lora_model:
  component_key: model
  variant_key: lora
  config:
    alpha: 1
    r: 2
    target_layers:
      - q_attn
      - k_attn
      - v_attn
      - o_attn
    model:
      instance_key: checkpointed_model
      pass_type: BY_REFERENCE


checkpointed_model:
  component_key: model
  variant_key: checkpointed
  config:
    checkpoint_loading:
      component_key: checkpoint_loading
      variant_key: torch
      config:
        device: 0
        precision: FP_32
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    checkpoint_path: /raid/s3/opengptx/models/modalities/2.7B_EN_DCLM/2.7B_EN_DCLM/eid_2024-08-29__11-59-57_6af5fa06-model-num_steps_103000-num_tokens_13500416000.bin


wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: lora_model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: FP_32
    sharding_strategy: FULL_SHARD
    block_names: [ GPT2Block ]

model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: gpt2
        weight_init_type: scaled #checked
        mean: 0.0 #checked
        std: 0.0158 #checked
        num_layers: ${model_raw.config.n_layer}

model_raw:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.training.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 32 #checked
    n_head_q: 32 #checked
    n_head_kv: 32 #checked
    ffn_hidden: 6784 #checked
    n_embd: 2560 #checked
    dropout: 0.0 #checked
    bias: false #checked
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform #checked
          config:
            n_embd: ${model_raw.config.n_embd}
            n_head: ${model_raw.config.n_head_q}
            seq_length_dim: -2
    attention_implementation: pytorch_flash
    activation_type: swiglu #checked
    attention_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 6e-4 #checked
    div_factor: 10 #checked
    final_div_factor: 1 #checked
    total_steps: 2124023 #checked 52199999488 tokens / (1 nodes * 2048 seq * 6 mbs * 2 gpus/node) = 106201 tokens ()
    pct_start: 0.012429 #checked corresponds to  52199999488 * 1,2429% of total tokens similar to megatron-lm training
    anneal_strategy: cos
    last_epoch:
      instance_key: skip_num_batches
      pass_type: BY_REFERENCE

num_steps_from_num_tokens:
  component_key: number_conversion
  variant_key: num_steps_from_num_tokens
  config:
    num_ranks: ${settings.cuda_env.world_size}
    local_micro_batch_size: ${settings.training.local_train_micro_batch_size}
    global_num_tokens: ${settings.training.global_num_seen_tokens}
    sequence_length: ${settings.training.sequence_length}

#optimizer:
#  component_key: optimizer
#  variant_key: checkpointed
#  config:
#    optimizer:
#      instance_key: optimizer_original
#      pass_type: BY_REFERENCE
#    wrapped_model:
#      instance_key: wrapped_model
#      pass_type: BY_REFERENCE
#    checkpoint_loading:
#      instance_key: checkpoint_loading
#      pass_type: BY_REFERENCE
#    checkpoint_path: /raid/s3/opengptx/models/modalities/2.7B_EN_DCLM/2.7B_EN_DCLM/eid_2024-08-29__11-59-57_6af5fa06-optimizer-num_steps_103000-num_tokens_13500416000.bin


optimizer:
  component_key: optimizer
  variant_key: adam_w #checked
  config:
    lr: 6e-4 #checked
    betas: [0.9, 0.95] #checked
    eps: 1e-8 #checked
    weight_decay: 1e-1 #checked
    weight_decay_groups_excluded: ["embedding", "layernorm"]
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0 #checked

batch_progress_subscriber:
  component_key: progress_subscriber
  # variant_key: dummy
  # config: {}
  variant_key: rich
  config:
    global_rank: ${settings.cuda_env.global_rank}
    global_num_seen_steps:
      instance_key: num_steps_from_num_tokens
      pass_type: BY_REFERENCE
    gradient_acc_steps: ${settings.training.gradient_acc_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE
evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    global_rank: ${settings.cuda_env.global_rank}
    project: 3B_fineweb_edu_50B_tokens
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: "."
    config_file_path: ${settings.config_file_path}
#
#checkpointed_model:
#  component_key: model
#  variant_key: checkpointed
#  config:
#    checkpoint_loading:
#      component_key: checkpoint_loading
#      variant_key: torch
#      config:
#        device: 0
#        precision: FP_32
#    model:
#      instance_key: model_raw
#      pass_type: BY_REFERENCE
#    checkpoint_path: /raid/s3/opengptx/models/modalities/2.7B_EN_DCLM/2.7B_EN_DCLM/finetuned/model.bin