settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpoint_saving_path: data/checkpoints
    train_dataset_path: ./data/lorem_ipsum.pbin
  intervals:
    training_log_interval_in_steps: 2
    checkpointing_interval_in_steps: 2
    evaluation_interval_in_steps: 2
  consistency_enforcement:
    enforce_tokens_per_step_consistency: true
    enforce_last_step_logged: false
    enforce_last_step_evaluated: false
    enforce_last_step_checkpointed: false
  step_profile: 
    gradient_accumulation_steps: 1
    local_train_micro_batch_size: 1
    sequence_length: 256
  training_target:
    num_target_tokens:      
      component_key: number_conversion
      variant_key: num_tokens_from_num_steps
      config:
        num_steps: ${settings.training_target.num_target_steps}
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.step_profile.local_train_micro_batch_size}
        sequence_length: ${settings.step_profile.sequence_length}
        gradient_accumulation_steps: ${settings.step_profile.gradient_accumulation_steps}
    num_target_steps:  # for the batch progress subscriber
      component_key: number_conversion
      variant_key: num_steps_from_num_samples
      config:
        num_ranks: ${settings.cuda_env.world_size}
        local_micro_batch_size: ${settings.step_profile.local_train_micro_batch_size}
        global_num_samples: ${settings.coca_example_settings.train_num_samples}
        gradient_accumulation_steps: ${settings.step_profile.gradient_accumulation_steps}
  training_progress: 
    global_num_seen_tokens: 0
    num_seen_steps: 0
    num_seen_samples: 0
    last_step: -1
  coca_example_settings:
    train_num_samples: 64
    val_num_samples: 32

collate_fn:
  component_key: collate_fn
  variant_key: coca_collator
  config:
    sample_keys:
      - images
      - ${settings.referencing_keys.sample_key}
    target_keys: []
    text_sample_key: ${settings.referencing_keys.sample_key}
    text_target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: dummy_dataset
  config:
    num_samples: ${settings.coca_example_settings.train_num_samples}
    sample_definition:
      - sample_key: images
        sample_shape: [3, 224, 224]
        sample_type: float
      - sample_key: input_ids
        sample_shape: [1024]
        sample_type: int

val_dataset:
  component_key: dataset
  variant_key: dummy_dataset
  config:
    num_samples: ${settings.coca_example_settings.val_num_samples}
    sample_definition:
      - sample_key: images
        sample_shape: [3, 224, 224]
        sample_type: float
      - sample_key: input_ids
        sample_shape: [1024]
        sample_type: int

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    dataloader_tag: train
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.step_profile.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: resumable_distributed_sampler
          config:
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: true
            seed: 42
            drop_last: true
            skip_num_global_samples: ${settings.training_progress.num_seen_samples}
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    dataloader_tag: val
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.step_profile.local_train_micro_batch_size}
        drop_last: true

        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            drop_last: true
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1 # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpoint_saving_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: FP_16
    sharding_strategy: FULL_SHARD
    block_names: [TransformerBlock, VisionTransformerBlock]

model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: coca
        weight_init_type: plain
        mean: 0.0
        std: 0.02

model_raw:
  component_key: model
  variant_key: coca
  config:
    prediction_key: logits
    vision_embd_prediction_key: vision_embeddings
    text_embd_prediction_key: text_embeddings
    vision_cls_prediction_key: vision_cls
    text_cls_prediction_key: text_cls
    vision_encoder_config:
      sample_key: images
      prediction_key: vision_embeddings
      img_size: 224
      n_classes: Null # Disable vision transformer head
      n_layer: 12
      attention_config:
        attention_engine_type: default_attention
      n_head: 12
      n_embd: 768
      dropout: 0.0
      patch_size: 16
      patch_stride: 16
      n_img_channels: 3
      add_cls_token: False
      bias: True
    text_decoder_config:
      sample_key: ${settings.referencing_keys.sample_key}
      prediction_key: ${loss_fn.config.prediction_key}
      block_size: 1024
      vocab_size: 50304
      n_layer_text: 12
      n_layer_multimodal_text: 12
      attention_config:
        attention_engine_type: default_attention
      n_head: 12
      ffn_hidden: 2048
      n_embd: 768
      dropout: 0.0
      bias: true
      activation: swiglu
      epsilon: 1e-5
    n_pool_head: 8
    n_vision_queries: 256
    bias_attn_pool: False
    epsilon_attn_pool: 1e-5

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 6e-4
    div_factor: 10
    final_div_factor: 1
    total_steps: ${settings.training_target.num_target_steps}
    pct_start: 0.01
    anneal_strategy: cos
    last_epoch: ${settings.training_progress.last_step}

optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    weight_decay_groups_excluded: []
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp_logging_only
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM

progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    global_rank: ${settings.cuda_env.global_rank}
    num_seen_steps: ${settings.training_progress.num_seen_steps}
    num_target_steps: ${settings.training_target.num_target_steps}
    train_dataloader_tag: ${train_dataloader.config.dataloader_tag}
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    global_rank: ${settings.cuda_env.global_rank}
    project: modalities
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: wandb_storage
    config_file_path: ${settings.config_file_path}