name: 🐛 Bug Report
description: Submit a bug report to help improve modalities
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug report, please make sure the issue hasn't already been addressed, by searching through [the existing and past issues](https://github.com/Modalities/modalities/issues).

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us.
      placeholder: modalities version, platform, python version, ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is. If relevant, add a minimal example so that we can reproduce the error by running the code. Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        # Sample code to reproduce the problem
        ```

        ```
        The error message you got, with the full traceback.
        ```
    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!