name: 🚀 Feature Request
description: Submit a proposal/request for a new modalities feature
labels: [ "feature" ]

body:
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature request
      description: |
        A clear and concise description of the feature proposal.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link it here, too.

  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!