settings:
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  grid_search:
    sequence_length: [4096, 8192]
    vocab_size: [50304]
    batch_size: [1, 2, 3, 4]

initialized_model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: fsdp_model
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: gpt2
        weight_init_type: scaled
        mean: 0.0
        std: 0.02
        num_layers: ${model_raw.config.n_layer}

fsdp_model:
  component_key: model
  variant_key: fsdp2_wrapped
  config:
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    device_mesh:
      instance_key: device_mesh
      pass_type: BY_REFERENCE
    mixed_precision_settings:
      param_dtype: BF_16
      reduce_dtype: BF_16
    block_names: [GPT2Block]

model_raw:
  component_key: model
  variant_key: gpt2
  config:
    use_meta_device: true
    use_weight_tying: false
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.grid_search.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: ${settings.grid_search.vocab_size}
    n_layer: 32
    n_head_q: 32
    n_head_kv: 8
    ffn_hidden: 21248
    n_embd: 4096
    dropout: 0.0
    bias: false
    attention_config:
      qkv_transforms:
      - type_hint: RotaryTransform
        config:
          n_embd: ${model_raw.config.n_embd}
          n_head: ${model_raw.config.n_head_q}
          seq_length_dim: -2
          base_freq: 500000
    attention_implementation: dao_flash
    activation_type: swiglu
    attention_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    ffn_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    lm_head_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05

device_mesh:
  component_key: device_mesh
  variant_key: default
  config:
    device_type: cuda
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: ${cuda_env:WORLD_SIZE} # i.e., fully sharded
    world_size: ${cuda_env:WORLD_SIZE}

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}


optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.0001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    weight_decay_groups_excluded: [embedding, layernorm]
    wrapped_model: 
      instance_key: initialized_model
      pass_type: BY_REFERENCE

dataset_batch_generator:
  component_key: dataset_batch_generator
  variant_key: random
  config:
    vocab_size: ${settings.grid_search.vocab_size}
    sequence_length: ${settings.grid_search.sequence_length}
    batch_size: ${settings.grid_search.batch_size}