settings:
  referencing_keys:
    sample_key: input_ids
    prediction_key: logits
  model_path: data/checkpoints/2.7B_EN_FW_EDU/eid_2024-08-08__13-52-31_a5609d8c-model-num_steps_106000-num_tokens_52101120000.bin
  device: 4
  sequence_length: 256

text_inference_component:
  component_key: inference_component
  variant_key: text
  config:
    device: ${settings.device}
    model:
      instance_key: checkpointed_model
      pass_type: BY_REFERENCE
    tokenizer:
      instance_key: tokenizer
      pass_type: BY_REFERENCE
    sequence_length: ${settings.sequence_length}
    eod_token: <eod>
    prompt_template: "{prompt_input}"
    temperature: 1.0
    # chat: false

checkpointed_model:
  component_key: model
  variant_key: checkpointed
  config: 
    checkpoint_loading:
      component_key: checkpoint_loading
      variant_key: torch
      config:
        device: ${settings.device}
        precision: BF16
    model:
      instance_key: model_raw
      pass_type: BY_REFERENCE
    checkpoint_path: ${settings.model_path}

model_raw:
  component_key: model
  variant_key: gpt2
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.sequence_length}
    prediction_key: ${settings.referencing_keys.prediction_key}
    vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 32 #checked
    n_head_q: 32 #checked
    n_head_kv: 32 #checked
    ffn_hidden: 6784 #checked
    n_embd: 2560 #checked
    dropout: 0.0 #checked
    bias: false #checked 
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform #checked
          config:
            n_embd: ${model_raw.config.n_embd}
            n_head: ${model_raw.config.n_head_q}
            seq_length_dim: -2
    attention_implementation: dao_flash
    activation_type: swiglu #checked
    attention_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config: 
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5
    ffn_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config: 
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5
    lm_head_norm:
      component_key: layer_norm
      variant_key: layer_norm
      config: 
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1e-5

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_sp_tokenizer
  config:
    tokenizer_model_file: data/checkpoints/2.7B_EN_FW_EDU/en_32k_tokenizer.model
