settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    global_training_log_interval_in_steps: 10000 # Needs to be a multiple of gradient_acc_steps
    global_checkpointing_interval_in_steps: 10000
    global_evaluation_interval_in_steps: 10000
    global_num_training_samples: 1925398
    global_num_seen_steps: 0
    do_apply_activation_checkpointing: true
    gradient_acc_steps: 1
    local_train_micro_batch_size: 256
    sequence_length: 512
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpointing_path: data/checkpoints


collate_fn:
  component_key: collate_fn
  variant_key: coca_collator
  config:
    sample_keys:
      - feats
      - feats_len
      - ${settings.referencing_keys.sample_key}
      - modality
    target_keys: []
    text_sample_key: ${settings.referencing_keys.sample_key}
    text_target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: arrow_dataset_audio
  config:
    type_: train
    audio_dataset_arrows: gertv-arrow-remove-na/train
    bpe_to_ind: bpe_to_ind_gertv_2000.pkl
    bpecodes: bpecodes_gertv_2000
    n_mels: 128
    block_size_audio_encoder: 500
    block_size_text_decoder: 512
    freq_domain_mask_length: 30
    time_domain_mask_length: 100

val_dataset:
  component_key: dataset
  variant_key: arrow_dataset_audio
  config:
    type_: val
    audio_dataset_arrows: gertv-arrow-remove-na/test
    bpe_to_ind: bpe_to_ind_gertv_2000.pkl
    bpecodes: bpecodes_gertv_2000
    n_mels: 128
    block_size_audio_encoder: 500
    block_size_text_decoder: 512
    freq_domain_mask_length: 30
    time_domain_mask_length: 100
    

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "train"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

val_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "val"
    dataset:
      instance_key: val_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            dataset:
              instance_key: val_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders:
  - instance_key: val_dataloader
    pass_type: BY_REFERENCE

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1 # -1 to save all checkpoints
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: fsdp
      config:
        checkpoint_path: ${settings.paths.checkpointing_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}
        # mixed_precision_settings: FP_16
        # sharding_strategy: FULL_SHARD
        # block_names: [TransformerBlock, AudioTransformer]


captioning_loss:
  component_key: loss
  variant_key: cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${model.config.prediction_key}
    tag: captioning_loss

contrastive_loss:
  component_key: loss
  variant_key: clip_loss
  config:
    prediction_key1: ${model.config.modality_cls_prediction_key}
    prediction_key2: ${model.config.text_cls_prediction_key}
    logit_scale_key: ${model.config.logit_scale_prediction_key}
    tag: contrastive_loss

loss_fn:
  - instance_key: captioning_loss
    pass_type: BY_REFERENCE
  - instance_key: contrastive_loss
    pass_type: BY_REFERENCE

wrapped_model:
  component_key: model
  variant_key: fsdp_wrapped
  config:
    model:
      instance_key: model
      pass_type: BY_REFERENCE
    sync_module_states: true
    mixed_precision_settings: FP_16
    sharding_strategy: FULL_SHARD
    block_names: [TransformerBlock, AudioTransformer]

model:
  component_key: model
  variant_key: coca
  config:
    prediction_key: logits
    audio_embd_prediction_key: modality_embeddings
    text_embd_prediction_key: text_embeddings
    audio_cls_prediction_key: modality_cls
    text_cls_prediction_key: text_cls
    logit_scale_prediction_key: logit_scale
    audio_encoder_config:
      sample_key: feats
      prediction_key: modality_embeddings
      block_size: 500
      n_mels: 128
      n_embd: 512
      n_heads: 4
      n_conformer_blocks: 3
      attention_config:
        attention_engine_type: default_attention
      pointwise_conv_kernel_size: 1
      depthwise_conv_kernel_size: 31
    text_decoder_config:
      sample_key: ${settings.referencing_keys.sample_key}
      prediction_key: ${model.config.prediction_key}
      block_size: 512
      vocab_size: 2134
      n_layer_text: 3
      n_layer_multimodal_text: 3
      attention_config:
        attention_engine_type: default_attention
      n_head: 4
      ffn_hidden: 1024
      n_embd: 512
      dropout: 0.0
      bias: true
      activation: fused_swiglu
      epsilon: 1e-5
    n_pool_head: 8
    n_queries: 256
    bias_attn_pool: False
    epsilon_attn_pool: 1e-5
    weight_init:
      mean: 0.0
      std: 0.02

scheduler:
  component_key: scheduler
  variant_key: onecycle_lr
  config:
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    max_lr: 6e-4
    div_factor: 10
    final_div_factor: 1
    total_steps: 962699
    pct_start: 0.01
    anneal_strategy: cos

optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 0.00001
    betas: [0.9, 0.95]
    eps: 1e-8
    weight_decay: 1e-1
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp
  config:
    wrapped_model:
      instance_key: wrapped_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    local_rank: ${settings.cuda_env.local_rank}
    # world_size: ${settings.cuda_env.world_size}
    global_num_seen_steps: ${settings.training.global_num_seen_steps}
    train_dataloader:
      instance_key: train_dataloader
      pass_type: BY_REFERENCE
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: wandb
  config:
    local_rank: ${settings.cuda_env.local_rank}
    project: modalities
    mode: OFFLINE
    experiment_id: ${settings.experiment_id}
    directory: "."
    config_file_path: ${settings.config_file_path}
