features:
  - jq_pattern: .transcript
    codec:
      type_hint: HfTokenizerCodec
      config:
        add_eos_token: true
        tokenizer:
          type_hint: GPT2TokenizerFast
          config:
            tokenizer_file: ./data/tokenizer/tokenizer.json
  - jq_pattern: .audio_path
    codec:
      type_hint: TorchaudioAudioCodec
      config:
        target_sample_rate: 16_000
        n_mels: 80
