settings:
  src_path: /workspaces/modalities/data/lorem_ipsum.jsonl
  dst_path: /workspaces/modalities/data/lorem_ipsum.pbin
  index_path: /workspaces/modalities/data/lorem_ipsum.idx
  jq_pattern: .text
  num_cpus: ${node_env:num_cpus}
  eod_token: <|endoftext|>

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: /workspaces/modalities/data/tokenizer/hf_gpt2
    padding: false
    max_length: 512
