settings:
  src_path: data/lorem_ipsum.jsonl
  dst_path: data/
  index_path: /workspaces/modalities/data/lorem_ipsum.idx
  jq_pattern: .text
  num_cpus: ${os_num_cpus}
  eod_token: ${tokenizer.config.special_tokens.eod_token}

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: /workspaces/modalities/data/tokenizer/hf_gpt2
    padding: false
    max_length: 512
    special_tokens:
      eod_token: <|EOD|>