sweep:
  local_train_micro_batch_size: [1,2,3,4]
  sequence_length: [2048, 4096, 8192]
  attention_implementation: [dao_flash, pytorch_flash, manual]
  fsdp2_input_model: [model_raw]
  num_target_steps: [20]

settings:
  experiment_id: ${modalities_env:experiment_id}
  config_file_path: ${modalities_env:config_file_path}
  config_folder_path : ${modalities_env:config_folder_path}
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
    prediction_key: logits
  cuda_env:
    local_rank: ${cuda_env:LOCAL_RANK}
    global_rank: ${cuda_env:RANK}
    world_size: ${cuda_env:WORLD_SIZE}
  paths:
    checkpoint_saving_path: ${modalities_env:config_folder_path}
  intervals:
    training_log_interval_in_steps: 1
    checkpointing_interval_in_steps: 1000
    evaluation_interval_in_steps: 1000
  consistency_enforcement:
    enforce_tokens_per_step_consistency: false
    enforce_last_step_logged: false
    enforce_last_step_evaluated: false
    enforce_last_step_checkpointed: false
  step_profile:
    gradient_accumulation_steps: 1
    local_train_micro_batch_size: ${sweep.local_train_micro_batch_size}
    sequence_length: ${sweep.sequence_length}
  training_target:
    num_target_tokens: 3744129024
    num_target_steps: ${sweep.num_target_steps}
  training_progress:
    global_num_seen_tokens: 0
    num_seen_steps: 0
    num_seen_samples: 0
    last_step: -1

collate_fn:
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}
train_dataset:
  component_key: dataset
  variant_key: combined
  config:
    datasets:
    - component_key: dataset
      variant_key: packed_mem_map_dataset_continuous
      config:
        raw_data_path: /leonardo_scratch/fast/EUHPC_D21_101/max_lue/data/gpt2_tokenized/000_00000.pbin
        sequence_length: ${settings.step_profile.sequence_length}
        sample_key: ${settings.referencing_keys.sample_key}  

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 4
    pin_memory: true
    dataloader_tag: train
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.step_profile.local_train_micro_batch_size}
        drop_last: true
        sampler:
          component_key: sampler
          variant_key: resumable_distributed_sampler
          config:
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: false
            seed: 42
            drop_last: true
            skip_num_global_samples: ${settings.training_progress.num_seen_samples}
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

eval_dataloaders: []

checkpoint_saving:
  component_key: checkpoint_saving
  variant_key: default
  config:
    checkpoint_saving_strategy:
      component_key: checkpoint_saving_strategy
      variant_key: save_k_most_recent_checkpoints_strategy
      config:
        k: -1
    checkpoint_saving_execution:
      component_key: checkpoint_saving_execution
      variant_key: dcp
      config:
        checkpoint_path: ${settings.paths.checkpoint_saving_path}
        global_rank: ${settings.cuda_env.global_rank}
        experiment_id: ${settings.experiment_id}

loss_fn:
  component_key: loss
  variant_key: clm_cross_entropy_loss
  config:
    target_key: ${settings.referencing_keys.target_key}
    prediction_key: ${settings.referencing_keys.prediction_key}

device_mesh:
  component_key: device_mesh
  variant_key: default
  config:
    device_type: cuda
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: -1
    world_size: ${settings.cuda_env.world_size}

app_state:
  component_key: app_state
  variant_key: raw
  config:
    model: 
      instance_key: initialized_model #  debugging_enriched_model
      pass_type: BY_REFERENCE
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
    lr_scheduler:
      instance_key: lr_scheduler
      pass_type: BY_REFERENCE

initialized_model:
  component_key: model
  variant_key: model_initialized
  config:
    model:
      instance_key: fsdp_model
      pass_type: BY_REFERENCE
    model_initializer:
      component_key: model_initialization
      variant_key: composed
      config:
        model_type: gpt2
        weight_init_type: scaled
        mean: 0.0
        std: 0.02
        num_layers: ${model_raw.config.n_layer}

fsdp_model:
  component_key: model
  variant_key: fsdp2_wrapped
  config:
    model:
      instance_key: ${sweep.fsdp2_input_model}
      pass_type: BY_REFERENCE
    device_mesh:
      instance_key: device_mesh
      pass_type: BY_REFERENCE
    mixed_precision_settings:
      param_dtype: BF_16
      reduce_dtype: BF_16
    block_names: [GPT2Block]

model_raw:
  component_key: model
  variant_key: gpt2
  config:
    use_meta_device: true
    use_weight_tying: false
    sample_key: ${settings.referencing_keys.sample_key}
    poe_type: NOPE
    sequence_length: ${settings.step_profile.sequence_length}
    prediction_key: ${loss_fn.config.prediction_key}
    vocab_size: 50304
    n_layer: 32
    n_head_q: 32
    n_head_kv: 8
    ffn_hidden: 16384
    n_embd: 4096
    dropout: 0.0
    bias: false
    attention_config:
      qkv_transforms:
        - type_hint: RotaryTransform
          config:
            n_embd: ${model_raw.config.n_embd}
            n_head: ${model_raw.config.n_head_q}
            seq_length_dim: -2
            base_freq: 500000
    attention_implementation: ${sweep.attention_implementation}
    activation_type: swiglu
    attention_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    ffn_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05
    lm_head_norm_config:
      norm_type: layer_norm
      config:
        normalized_shape: ${model_raw.config.n_embd}
        eps: 1.0e-05

lr_scheduler:
  component_key: scheduler
  variant_key: linear_lr
  config:
    start_factor: 0.000001
    end_factor: 1.0
    total_iters: 500
    optimizer:
      instance_key: optimizer
      pass_type: BY_REFERENCE
optimizer:
  component_key: optimizer
  variant_key: adam_w
  config:
    lr: 3e-4
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 0.1
    weight_decay_groups_excluded:
      - embedding
      - layernorm
    wrapped_model:
      instance_key: initialized_model
      pass_type: BY_REFERENCE

gradient_clipper:
  component_key: gradient_clipper
  variant_key: fsdp2
  config:
    wrapped_model:
      instance_key: initialized_model
      pass_type: BY_REFERENCE
    norm_type: P2_NORM
    max_norm: 1.0

progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
  config:
    global_rank: ${settings.cuda_env.global_rank}
    num_seen_steps: ${settings.training_progress.num_seen_steps}
    num_target_steps: ${settings.training_target.num_target_steps}
    train_dataloader_tag: ${train_dataloader.config.dataloader_tag}
    eval_dataloaders:
      instance_key: eval_dataloaders
      pass_type: BY_REFERENCE

evaluation_subscriber:
  component_key: results_subscriber
  variant_key: to_disc
  config:
    output_file_path: ${settings.paths.checkpoint_saving_path}/evaluation_results.jsonl

mfu_calculator:
  component_key: mfu_calculator
  variant_key: gpt2
  config:
    n_layer: ${model_raw.config.n_layer}
    sequence_length: ${settings.step_profile.sequence_length}
    n_embd: ${model_raw.config.n_embd}
    world_size: ${settings.cuda_env.world_size}
    wrapped_model:
      instance_key: initialized_model
      pass_type: BY_REFERENCE