import hashlib
import time
import warnings
from datetime import datetime
from enum import Enum
from pathlib import Path
from types import TracebackType
from typing import Callable, Generic, Optional, Type, TypeVar

import torch
import torch.distributed as dist
from pydantic import ValidationError
from torch.distributed.fsdp import FSDPModule as FSDP2
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.types import Number

from modalities.exceptions import TimeRecorderStateError
from modalities.running_env.fsdp.reducer import Reducer
from modalities.utils.typing import FSDPX


def print_rank_0(message: str):
    """If torch.distributed is initialized, print only on rank 0."""
    if torch.distributed.is_initialized():
        if torch.distributed.get_rank() == 0:
            print(message, flush=True)
    else:
        print(message, flush=True)


def warn_rank_0(message: str):
    """If torch.distributed is initialized, print only on rank 0."""
    message_with_color_code = f"\033[91m {message} \033[00m"
    if torch.distributed.is_initialized():
        if torch.distributed.get_rank() == 0:
            warnings.warn(message_with_color_code)
    else:
        warnings.warn(message_with_color_code)


def parse_enum_by_name(name: str, enum_type: Type[Enum]) -> Enum:
    try:
        return enum_type[name]
    except KeyError:
        raise ValidationError(f"Invalid {enum_type} member name: {name}")


def get_experiment_id_of_run(
    config_file_path: Path, hash_length: Optional[int] = 8, max_experment_id_byte_length: Optional[int] = 1024
) -> str:
    """Create a unique experiment ID for the current run on rank 0 and broadcast it to all ranks.
    Internally, the experiment ID is generated by hashing the configuration file path and appending
    the current date and time.
    The experiment ID is then converted to a byte array (with maximum length of max_experment_id_byte_length) and
    broadcasted to all ranks. In the unlikely case of the experiment ID being too long, a ValueError is raised
    and max_experment_id_byte_length must be increased. Each rank then decodes the byte array to the original
    string representation and returns it. Having a globally synced experiment ID is mandatory for
    saving files / checkpionts in a distributed training setup.

    Args:
        config_file_path (Path): Path to the configuration file.
        hash_length (Optional[int], optional): Defines the char length of the commit hash. Defaults to 8.
        max_experment_id_byte_length (Optional[int], optional): Defines max byte length of the experiment_id
            to be shared to other ranks. Defaults to 1024.

    Returns:
        str: The experiment ID.
    """

    def get_experiment_id_from_config(config_file_path: Path, hash_length: Optional[int] = 8) -> str:
        """Create experiment ID including the date and time for file save uniqueness
        example: 2022-05-07__14-31-22_fdh1xaj2'
        """
        hash = hashlib.sha256(str(config_file_path).encode()).hexdigest()[:hash_length]
        date_of_run = datetime.now().strftime("%Y-%m-%d__%H-%M-%S")
        experiment_id = f"{date_of_run}_{hash}"
        return experiment_id

    rank = dist.get_rank()
    if rank == 0:
        # Generate a unique folder name
        experimenet_id = get_experiment_id_from_config(config_file_path, hash_length)
        experimenet_id_bytes = experimenet_id.encode("utf-8")
        if len(experimenet_id_bytes) > max_experment_id_byte_length:
            raise ValueError(
                f"Experiment ID is too long: {len(experimenet_id_bytes)} bytes, "
                f"max length is {max_experment_id_byte_length} bytes"
            )
        print(f"Rank 0 generated experiment_id: {experimenet_id}")
    else:
        experimenet_id_bytes = bytearray(max_experment_id_byte_length)  # Preallocate buffer for receiving

    # Ensure all ranks have the same folder name
    experment_id_tensor = torch.tensor(
        list(experimenet_id_bytes) + [0] * (max_experment_id_byte_length - len(experimenet_id_bytes)), dtype=torch.uint8
    ).cuda()
    dist.broadcast(experment_id_tensor, src=0)

    # Decode on all ranks
    experiment_id = experment_id_tensor.cpu().numpy().tobytes().decode("utf-8").rstrip("\x00")
    print(f"Rank {rank} received experiment_id: {experiment_id}")
    return experiment_id


def format_metrics_to_gb(item):
    """quick function to format numbers to gigabyte and round to 4 digit precision"""
    g_gigabyte = 1024**3
    metric_num = item / g_gigabyte
    metric_num = round(metric_num, ndigits=4)
    return metric_num


def get_local_number_of_trainable_parameters(model: torch.nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def get_total_number_of_trainable_parameters(model: FSDPX) -> Number:
    if isinstance(model, FSDP):
        num_params = get_local_number_of_trainable_parameters(model)
        num_params_tensor = torch.tensor(num_params).cuda()
        dist.all_reduce(num_params_tensor, op=dist.ReduceOp.SUM)
        total_num_params = num_params_tensor.item()
        # For HYBRID sharding, divide by sharding factor to get the correct number of parameters
        # TODO: Define constant instead of hardcoding string
        # Assumes that CUDA is available and each node has the same number of GPUs
        # Note: Per default FSDP constructs process groups for the user to shard intra-node and replicate inter-node.
        # However, users can also provide their own sharding process groups (currently not supported in Modalities)
        # which would require to adapt the code.
        if model.sharding_strategy.name == "NO_SHARD":
            sharding_factor = dist.get_world_size()
        if model.sharding_strategy.name == "HYBRID_SHARD":
            sharding_factor = dist.get_world_size() // torch.cuda.device_count()
        elif model.sharding_strategy.name == "FULL_SHARD":
            sharding_factor = 1
        total_num_params = total_num_params // sharding_factor
        return total_num_params
    elif isinstance(model, FSDP2):
        return -1  # TODO We need to fix this by calculating the correct value based on the device-mesh!


class TimeRecorderStates(Enum):
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"


class TimeRecorder:
    """Class with context manager to record execution time"""

    def __init__(self):
        self.delta_t: float = 0
        self.time_s: float = -1
        self._state: TimeRecorderStates = TimeRecorderStates.STOPPED

    def start(self):
        if self._state == TimeRecorderStates.RUNNING:
            raise TimeRecorderStateError("Cannot start a running TimeRecorder.")
        self.time_s = time.perf_counter()
        self._state = TimeRecorderStates.RUNNING

    def stop(self):
        if self._state == TimeRecorderStates.STOPPED:
            raise TimeRecorderStateError("Cannot stop an already stopped TimeRecorder.")
        self.delta_t += time.perf_counter() - self.time_s
        self._state = TimeRecorderStates.STOPPED

    def reset(self):
        if self._state == TimeRecorderStates.RUNNING:
            raise TimeRecorderStateError("Can only reset a stopped TimeRecorder.")
        self.delta_t = 0
        self.time_s = -1

    def __enter__(self):
        self.start()
        return self

    def __exit__(
        self,
        type,  # type: ignore
        value: None | BaseException,
        traceback: None | TracebackType,
    ):
        self.stop()

    def __repr__(self) -> str:
        return f"{self.delta_t}s"


T = TypeVar("T")


class Aggregator(Generic[T]):
    def __init__(self):
        self.key_to_value: dict[T, torch.Tensor] = {}

    def add_value(self, key: T, value: torch.Tensor):
        if key not in self.key_to_value:
            self.key_to_value[key] = value
        else:
            self.key_to_value[key] += value

    def remove_key(self, key: T):
        self.key_to_value.pop(key)

    def remove_keys(self):
        self.key_to_value = {}

    def get_all_reduced_value(
        self,
        key: T,
        reduce_operation: dist.ReduceOp.RedOpType = dist.ReduceOp.SUM,
        postprocessing_fun: None | Callable[[torch.Tensor], torch.Tensor] = None,
    ) -> torch.Tensor:
        # we clone the value so that we can always resync the value without side-effects
        cloned_value = self.key_to_value[key].clone()
        value = Reducer.reduce(
            tensor=cloned_value,
            operation=reduce_operation,
            post_processing_fun=postprocessing_fun,  # lambda t: t[0] / t[1],
        )
        return value


def get_module_class_from_name(module: torch.nn.Module, name: str) -> Type[torch.nn.Module] | None:
    """From Accelerate source code
    (https://github.com/huggingface/accelerate/blob/1f7a79b428749f45187ec69485f2c966fe21926e/src/accelerate/utils/dataclasses.py#L1902)
    Gets a class from a module by its name.

    Args:
        module (`torch.nn.Module`): The module to get the class from.
        name (`str`): The name of the class.
    """
    modules_children = list(module.children())
    if module.__class__.__name__ == name:
        return module.__class__
    elif len(modules_children) == 0:
        return
    else:
        for child_module in modules_children:
            module_class = get_module_class_from_name(child_module, name)
            if module_class is not None:
                return module_class
