name: "Build Sphinx Documentation"

on:
  push:
    branches:
      - ci/setup

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check path
      run: |
        pwd
        ls -alsh
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"