name: "Build Sphinx Documentation"

on:
  push:
    branches:
      - ci/setup

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pip install myst-parser
        pip install -e .
        pip install sphinx-rtd-theme
    - name: "Parse into HTML"
      run: |
        sphinx-build -M html docs/source/ docs/build/
    