name: "Build Sphinx Documentation"

on:
  push:
    branches:
      - ci/setup

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check path
      run: |
        pip install myst-parser
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"