name: "Build Sphinx Documentation"

on:
  push:
    branches:
      - ci/setup
      # - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pip install myst-parser
        pip install .
        pip install sphinx-rtd-theme sphinx-autodoc-typehints sphinx-click sphinx-automodapi texext
    - name: "Parse into HTML"
      run: |
        sphinx-build -M html docs/source/ docs/build/
        sphinx-apidoc -o docs/source/api src/modalities

    