name: Linting

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [review_requested, ready_for_review, auto_merge_enabled]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
    - name: Analysing the code with pre-commit
      run: |
        pre-commit run --all-files
